repos:
  - repo: https://github.com/alvistar/dartfmt-precommit
    rev: master
    hooks:
      - id: dartfmt

  - repo: https://github.com/alvistar/embedmd-precommit
    rev: master
    hooks:
      - id: embedmd
        files: ^README.md$