name: dart_algorand
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Alessandro Viganò <alvistar@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  msgpack_dart: ^0.0.6
  base32: 1.1.1
  pointycastle: 1.0.2
  pinenacl: ^0.1.2
  collection: ^1.14.11
  dio: ^3.0.9
#    git:
#      url: git://github.com/flutterchina/dio.git
#      path: dio
#      ref: master
  built_value: ^7.0.9
  built_collection: ^4.3.2
  equatable: ^1.1.0

#  path: ^1.6.0

dev_dependencies:
  build_runner: ^1.7.4
  built_value_generator: ^7.0.9
  pedantic: ^1.8.0
  test: ^1.6.0
