name: dart_algorand
description: >
  A dart library for interacting with the Algorand network.

  Algorand is an open source permissionless public blockchain based on
  a pure proof-of-stake consensus protocol.
version: 0.9.8
homepage: https://github.com/alvistar/dart_algorand

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  msgpack_dart: ^1.0.0
  base32: ^2.0.0-nullsafety.1
  pointycastle: ^3.0.1
  pinenacl: ^0.2.0
  collection: ^1.14.11
  dio: ^4.0.0
  built_value: ^8.0.5
  built_collection: ^5.0.0
  equatable: ^2.0.0
  http: ^0.13.1
  meta: ^1.1.8
  convert: ^3.0.0

dev_dependencies:
  build_runner:
  pedantic: ^1.8.0
  test: ^1.6.0
